// gen_cp932 — emit native/core/cp932_tables.h from .NET's cp932 encoding.
//
// The C# core (DokuroScript.Core/Stcm2Text.cs) is the reference behavior for
// this project: it encodes/decodes via Encoding.GetEncoding(932) on .NET.
// The C++ rewrite must be byte-exact with it, so instead of hand-writing a
// table (or trusting glibc's iconv, which differs on NEC/IBM extension rows)
// we GENERATE the C++ tables from .NET itself and embed them. Regenerate with:
//
//   nix develop --command dotnet run --project tools/gen_cp932 -- <outdir>
//
// Emits:
//   cp932_tables.h  — dense decode table (pair -> codepoint+1, 0=invalid),
//                      sorted encode table (codepoint -> 1 or 2 bytes),
//                      single-byte decode/encode maps.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

class Gen
{
    static Encoding _strict;
    static Encoding _lenient;

    static void Main(string[] args)
    {
        string outDir = args.Length > 0 ? args[0] : ".";
        try
        {
            var t = Type.GetType("System.Text.CodePagesEncodingProvider, System.Text.Encoding.CodePages");
            var inst = t?.GetProperty("Instance")?.GetValue(null) as EncodingProvider;
            if (inst != null) Encoding.RegisterProvider(inst);
        }
        catch { }

        _strict = Encoding.GetEncoding(932,
            EncoderFallback.ExceptionFallback, DecoderFallback.ExceptionFallback);
        _lenient = Encoding.GetEncoding(932,
            EncoderFallback.ReplacementFallback, DecoderFallback.ReplacementFallback);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by tools/gen_cp932 (from .NET Encoding.GetEncoding(932)).");
        sb.AppendLine("// DO NOT EDIT — regenerate instead. See tools/gen_cp932/Program.cs.");
        sb.AppendLine("#pragma once");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();

        // ---- single-byte decode: byte -> codepoint (0 = invalid) ----
        var singleDec = new ushort[256];
        for (int b = 0; b < 256; b++)
        {
            try
            {
                string s = _strict.GetString(new byte[] { (byte)b });
                if (s.Length != 1) throw new Exception($"single byte {b:X2} decoded to {s.Length} chars");
                singleDec[b] = (ushort)(s[0] + 1);
            }
            catch { singleDec[b] = 0; }
        }

        // ---- double-byte decode: lead/trail -> codepoint (0 = invalid) ----
        var pair = new Dictionary<int, char>(); // (lead<<8)|trail -> char
        for (int lead = 0; lead < 256; lead++)
        {
            bool leadOk = lead >= 0x81 && lead <= 0x9F || lead >= 0xE0 && lead <= 0xFC;
            if (!leadOk) continue;
            for (int trail = 0; trail < 256; trail++)
            {
                bool trailOk = trail >= 0x40 && trail <= 0x7E || trail >= 0x80 && trail <= 0xFC;
                if (!trailOk) continue;
                try
                {
                    string s = _strict.GetString(new byte[] { (byte)lead, (byte)trail });
                    if (s.Length != 1) throw new Exception($"pair {lead:X2}{trail:X2} decoded to {s.Length} chars");
                    pair[(lead << 8) | trail] = s[0];
                }
                catch { /* invalid pair */ }
            }
        }

        // ---- encode: codepoint -> bytes (exception fallback = not encodable) ----
        var enc = new SortedDictionary<char, ushort>(); // char -> code (<0x100 = 1 byte, else (b0<<8)|b1)
        for (int cp = 0x00; cp <= 0xFFFF; cp++)
        {
            if (cp >= 0xD800 && cp <= 0xDFFF) continue; // surrogates: never encodable
            char c = (char)cp;
            try
            {
                byte[] b = _strict.GetBytes(new char[] { c });
                if (b.Length == 1) enc[c] = b[0];
                else if (b.Length == 2) enc[c] = (ushort)((b[0] << 8) | b[1]);
                else throw new Exception($"char U+{cp:X4} encoded to {b.Length} bytes");
            }
            catch { }
        }

        // ---- emit single-byte decode ----
        sb.AppendLine("// byte -> codepoint+1 (0 = invalid). Covers ASCII + half-width katakana.");
        sb.AppendLine("static const uint16_t kCp932SingleDecode[256] = {");
        for (int i = 0; i < 256; i += 8)
        {
            sb.Append("    ");
            for (int j = 0; j < 8; j++) sb.Append($"0x{singleDec[i + j]:X4}, ");
            sb.AppendLine();
        }
        sb.AppendLine("};");
        sb.AppendLine();

        // ---- emit double-byte decode (dense, 256*256) ----
        sb.AppendLine("// (lead<<8)|trail -> codepoint+1 (0 = invalid).");
        sb.AppendLine("static const uint16_t kCp932PairDecode[65536] = {");
        int pairs = 0;
        for (int lead = 0; lead < 256; lead++)
        {
            bool leadOk = lead >= 0x81 && lead <= 0x9F || lead >= 0xE0 && lead <= 0xFC;
            for (int trail = 0; trail < 256; trail += 8)
            {
                sb.Append("    ");
                for (int j = 0; j < 8; j++)
                {
                    int key = (lead << 8) | (trail + j);
                    ushort v = 0;
                    if (leadOk)
                    {
                        bool trailOk = (trail + j) >= 0x40 && (trail + j) <= 0x7E || (trail + j) >= 0x80 && (trail + j) <= 0xFC;
                        if (trailOk && pair.TryGetValue(key, out char c)) { v = (ushort)(c + 1); pairs++; }
                    }
                    sb.Append($"0x{v:X4}, ");
                }
                sb.AppendLine();
            }
        }
        sb.AppendLine("};");
        sb.AppendLine($"// {pairs} double-byte pairs");

        // ---- emit encode table (single global sort by codepoint) ----
        sb.AppendLine();
        sb.AppendLine("// codepoint -> on-disk bytes. Encodable chars only (sorted by codepoint).");
        sb.AppendLine("struct Cp932EncEntry { uint16_t ch; uint16_t code; }; // code: <0x100 = 1 byte, else (b0<<8)|b1");
        sb.AppendLine("static const Cp932EncEntry kCp932EncodeTable[] = {");
        int singles = 0;
        foreach (var kv in enc)
        {
            bool one = kv.Value < 0x100;
            if (one) singles++;
            sb.AppendLine($"    {{ 0x{(int)kv.Key:X4}, 0x{kv.Value:X4} }}, // U+{(int)kv.Key:X4} = {(one ? $"0x{kv.Value:X2}" : $"0x{kv.Value >> 8:X2} 0x{kv.Value & 0xFF:X2}")}");
        }
        sb.AppendLine("};");
        sb.AppendLine($"// {enc.Count} encodable codepoints ({singles} single-byte, {enc.Count - singles} double-byte)");

        // ---- sanity statistics ----
        int twoByteChars = enc.Count - singles;
        Console.WriteLine($"single-byte decode: {(singleDec as IEnumerable<ushort>).Count(v => v != 0)} valid");
        Console.WriteLine($"double-byte decode: {pairs} valid pairs");
        Console.WriteLine($"encode: {singles} single-byte, {twoByteChars} double-byte codepoints");

        // self-check: every decodable pair re-encodes back to itself
        int roundTripFail = 0;
        foreach (var kv in pair)
        {
            char c = kv.Value;
            byte[] b = _strict.GetBytes(new char[] { c });
            if (b.Length == 2 && ((b[0] << 8) | b[1]) != kv.Key) roundTripFail++;
            if (b.Length == 1) roundTripFail++; // multi-mapped char encoded single
        }
        Console.WriteLine($"decode->encode mismatches: {roundTripFail}");
        if (roundTripFail > 0) Console.WriteLine("NOTE: some chars map to multiple byte pairs; decode table uses .NET's GetString choice, encode uses .NET's GetBytes choice.");

        string outPath = Path.Combine(outDir, "cp932_tables.h");
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"wrote {outPath} ({sb.Length} bytes)");
    }
}
